language: python
python:
  - "3.10-dev"
cache: pip
# command to install dependencies
install:
  - pip install -r requirements.txt
  - pip install coverage flake8 codecov

addons:
  postgresql: "14"
  apt:
    packages:
    - postgresql-14
    - postgresql-client-14

services:
  - postgresql

env:
  global:
  - PGPORT=5433
  - PGUSER=travis
  jobs:
    - DB_PORT=5433 DB_USERNAME=travis

# command to run tests
script:
  - flake8
  - coverage run manage.py test
after_success:
  - codecov
